import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { QuoteStatus } from '@prisma/client';
import { Decimal } from '@prisma/client/runtime/library';
import { AuditService } from '../audit/audit.service'; import { PrismaService } from '../prisma.service'; import { TenantContextService } from '../tenancy/tenant-context.service'; import { CreateQuoteDto, QuoteLineDto, UpdateQuoteDto } from './dto/quote.dto';

@Injectable()
export class QuotesService {
  constructor(private readonly prisma: PrismaService, private readonly tenant: TenantContextService, private readonly audit: AuditService) {}
  async list() { return this.prisma.quote.findMany({ where: this.scope(), include: { contact: { select: { legalName: true } } }, orderBy: { createdAt: 'desc' } }); }
  async get(id: string) { const q = await this.prisma.quote.findFirst({ where: { id, ...this.scope() }, include: { lines: { orderBy: { position: 'asc' } } } }); if (!q) throw new NotFoundException('Quote not found'); return q; }
  async create(input: CreateQuoteDto) { const data = await this.build(input); const scope = this.scope(); const q = await this.prisma.quote.create({ data: { ...scope, ...data, lines: { create: data.lines.map((line) => ({ ...line, ...scope })) } }, include: { lines: true } }); await this.audit.record('quote.created', 'quote', q.id); return q; }
  async update(id: string, input: UpdateQuoteDto) { const q = await this.get(id); if (q.status !== QuoteStatus.DRAFT) throw new ForbiddenException('Only draft quotes may be edited'); const data = await this.build(input); const scope = this.scope(); const updated = await this.prisma.$transaction((tx) => tx.quote.update({ where: { id }, data: { ...data, lines: { deleteMany: {}, create: data.lines.map((line) => ({ ...line, ...scope })) } }, include: { lines: true } })); await this.audit.record('quote.updated', 'quote', id); return updated; }
  async changeStatus(id: string, status: QuoteStatus) { const q = await this.get(id); const allowed: Record<QuoteStatus, QuoteStatus[]> = { DRAFT: [QuoteStatus.SENT, QuoteStatus.CANCELLED], SENT: [QuoteStatus.ACCEPTED, QuoteStatus.REJECTED, QuoteStatus.EXPIRED, QuoteStatus.CANCELLED], ACCEPTED: [], REJECTED: [], EXPIRED: [], CANCELLED: [] }; if (!allowed[q.status].includes(status)) throw new BadRequestException(`Cannot change ${q.status} to ${status}`); const updated = await this.prisma.quote.update({ where: { id }, data: { status } }); await this.audit.record('quote.status_changed', 'quote', id, { from: q.status, to: status }); return updated; }
  private async build(input: CreateQuoteDto) { if (!input.lines.length) throw new BadRequestException('A quote needs at least one line'); const scope = this.scope(); const contact = await this.prisma.contact.findFirst({ where: { id: input.contactId, ...scope, isCustomer: true, status: 'ACTIVE' } }); if (!contact) throw new BadRequestException('Quote contact must be an active customer in this company'); const lines = input.lines.map((l, i) => line(l, i + 1)); const totals = lines.reduce((a, l) => ({ subtotal: a.subtotal.plus(l.gross), discountTotal: a.discountTotal.plus(l.discount), taxTotal: a.taxTotal.plus(l.taxAmount), total: a.total.plus(l.totalAmount) }), { subtotal: new Decimal(0), discountTotal: new Decimal(0), taxTotal: new Decimal(0), total: new Decimal(0) }); return { contactId: input.contactId, issueDate: new Date(input.issueDate), validUntil: input.validUntil ? new Date(input.validUntil) : null, currency: input.currency ?? 'EUR', notes: input.notes?.trim() || null, ...totals, lines }; }
  private scope() { const { organizationId, companyId } = this.tenant.required; if (!companyId) throw new BadRequestException('x-company-id is required'); return { organizationId, companyId }; }
}
function line(input: QuoteLineDto, position: number) { const quantity = new Decimal(input.quantity); const unitPrice = new Decimal(input.unitPrice); const gross = quantity.mul(unitPrice).toDecimalPlaces(2); const discount = gross.mul(input.discountPct ?? 0).div(100).toDecimalPlaces(2); const netAmount = gross.minus(discount); const taxAmount = netAmount.mul(input.taxRate ?? 0).div(100).toDecimalPlaces(2); return { position, catalogItemId: input.catalogItemId, description: input.description.trim(), quantity, unitPrice, discountPct: new Decimal(input.discountPct ?? 0), taxRate: new Decimal(input.taxRate ?? 0), netAmount, taxAmount, totalAmount: netAmount.plus(taxAmount), gross, discount }; }
